# Application Configuration
app:
  env: "development"
  auth: "firebase" #firebase, custom
  port: 3000
  version: "v99"

# Firebase 
firebase:
  enabled: true
  project_id: "my-game-gcp-project"
  credentials_file_path: "" # 本地開發可填寫路徑；在 GCP Cloud Run 環境留空即可（自動套用 GCP ADC 認證）
  use_firestore: true
  use_storage: false
  storage_bucket: "my-game-bucket.appspot.com"
  use_message: false

# Database Configuration
database:
  master:
    host: "postgres"
    port: 5432
    user: "game_user"
    password: "game_password"
    dbname: "game_db"
  readonly:
    host: "postgres"
    port: 5432
    user: "game_user"
    password: "game_password"
    dbname: "game_db"

# Redis Configuration
redis:
  host: "redis"
  port: 6379
  password: "redis_password"
  db: 0

# Elasticsearch Configuration
elastic:
  addresses:
    - "http://elasticsearch:9200"
  username: "elastic"
  password: "local_pass"

# Session Configuration
session:
  secret_key: "c2VjcmV0LWtleS1mb3ItZGV2ZWxvcG1lbnQtMzA4OQ" # 32-bytes (256-bit) Base64 encoded secret
  issuer: "api-library"
  access_ttl: "15m"
  refresh_ttl: "168h"

# Webhook Configuration
webhook:
  meta_payment:
    verify_token: "123456789"
    app_secret: "app_secret"
