FROM golang:1.26-alpine AS builder
#RUN apk update && apk add --no-cache ca-certificates tzdata

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /app/cloud-run ./internal/cmd/gcp_cloud_run

FROM alpine:latest
RUN apk update && apk add --no-cache ca-certificates tzdata
#RUN rm -rf /var/cache/apk/*

# (選用) 設定預設時區
#ENV TZ=Asia/Taipei

WORKDIR /app
COPY --from=builder /app/cloud-run .
COPY config.yaml ./config.yaml

ENTRYPOINT ["./cloud-run"]
