package quest

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

// data/quests.json is generated by the Unity editor menu
// "Tools > Quests > Export Catalog to api-library" (QuestCatalogExporter.cs). Do not edit by hand.
//
//go:embed data/quests.json
var catalogJSON []byte

// Catalog is the server's copy of the quest table: ids, step order, checkpoints,
// conditions and rewards. Presentation (anchors, text, conversations) stays in the client.
type Catalog struct {
	Version    int          `json:"version"`
	ExportedAt string       `json:"exportedAt"`
	Quests     []Definition `json:"quests"`

	byID map[string]*Definition
}

type Definition struct {
	ID       string    `json:"id"`
	Type     QuestType `json:"type"`
	Initial  bool      `json:"initial"`            // started for a fresh account
	FollowUp string    `json:"followUp,omitempty"` // started when this quest completes
	Steps    []Step    `json:"steps"`
}

type Step struct {
	ID         string    `json:"id"`
	Checkpoint bool      `json:"checkpoint"`
	Condition  Condition `json:"condition"`
	Rewards    []Reward  `json:"rewards"`
}

type Condition struct {
	EventType EventType `json:"eventType"`
	Key       string    `json:"key"`
	Target    float64   `json:"target"`
}

type Reward struct {
	Type   RewardType `json:"type"`
	Key    string     `json:"key"`
	Amount float64    `json:"amount"`
}

// LoadCatalog parses and validates the embedded catalog.
func LoadCatalog() (*Catalog, error) {
	return ParseCatalog(catalogJSON)
}

func ParseCatalog(data []byte) (*Catalog, error) {
	var c Catalog
	if err := json.Unmarshal(data, &c); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrInvalidCatalog, err)
	}
	if err := c.validate(); err != nil {
		return nil, err
	}
	return &c, nil
}

func (c *Catalog) Get(id string) (*Definition, bool) {
	d, ok := c.byID[id]
	return d, ok
}

// IsUnlockedBy reports whether questID may be started given the completed quests:
// initial quests always, others only as the follow-up of a completed quest.
func (c *Catalog) IsUnlockedBy(questID string, completed func(id string) bool) bool {
	d, ok := c.byID[questID]
	if !ok {
		return false
	}
	if d.Initial {
		return true
	}
	for i := range c.Quests {
		if c.Quests[i].FollowUp == questID && completed(c.Quests[i].ID) {
			return true
		}
	}
	return false
}

func (c *Catalog) validate() error {
	c.byID = make(map[string]*Definition, len(c.Quests))
	for i := range c.Quests {
		d := &c.Quests[i]
		if d.ID == "" {
			return fmt.Errorf("%w: quest #%d has no id", ErrInvalidCatalog, i)
		}
		if _, dup := c.byID[d.ID]; dup {
			return fmt.Errorf("%w: duplicate quest id %q", ErrInvalidCatalog, d.ID)
		}
		switch d.Type {
		case QuestTypeTutorial, QuestTypeChapter, QuestTypeGoal:
		default:
			return fmt.Errorf("%w: quest %q has unknown type %q", ErrInvalidCatalog, d.ID, d.Type)
		}
		if len(d.Steps) == 0 {
			return fmt.Errorf("%w: quest %q has no steps", ErrInvalidCatalog, d.ID)
		}
		if err := validateSteps(d); err != nil {
			return err
		}
		c.byID[d.ID] = d
	}

	for i := range c.Quests {
		d := &c.Quests[i]
		if d.FollowUp == "" {
			continue
		}
		if _, ok := c.byID[d.FollowUp]; !ok {
			return fmt.Errorf("%w: quest %q follow-up %q does not exist", ErrInvalidCatalog, d.ID, d.FollowUp)
		}
	}
	return nil
}

func validateSteps(d *Definition) error {
	seen := make(map[string]bool, len(d.Steps))
	for i, s := range d.Steps {
		if s.ID == "" {
			return fmt.Errorf("%w: quest %q step #%d has no id", ErrInvalidCatalog, d.ID, i)
		}
		if seen[s.ID] {
			return fmt.Errorf("%w: quest %q has duplicate step id %q", ErrInvalidCatalog, d.ID, s.ID)
		}
		seen[s.ID] = true

		switch s.Condition.EventType {
		case EventActionDone, EventCountIncrement, EventStateChanged, EventAmountEarned, EventConversationEnded:
		default:
			return fmt.Errorf("%w: quest %q step %q has unknown event type %q", ErrInvalidCatalog, d.ID, s.ID, s.Condition.EventType)
		}

		for _, r := range s.Rewards {
			switch r.Type {
			case RewardCash, RewardPull, RewardUnlock:
			default:
				return fmt.Errorf("%w: quest %q step %q has unknown reward type %q", ErrInvalidCatalog, d.ID, s.ID, r.Type)
			}
		}
	}
	return nil
}
